### ISSUE TITLE
Schedule widget does not respect locale attribute

### ISSUE THREAD

**Issue by MikkCZ** [pretalx/schedule#20]
STR:
- Go to `/orga/event/<event-slug>/settings/widget`
- Select _Czech/čeština_ as widget language.
- Generate the widget.
- Embed the widget into website.

What happens:
- The schedule is rendered in English locale (AM/PM time format, English date labels etc.)

Expected behavior:
- The schedule is fully localized to Czech (or any selected locale).

---

I noticed, that `<html lang="cs">` attributes changes the language of the room informational tooltip to Czech (with the attribute missing, the tooltips were in English). But the rest of the widget stays in English.

Also the generated code snippet includes `schedule/widget/v2.en.js` script file. I changed it to `schedule/widget/v2.cs.js`, also with no effect.

**Comment by MikkCZ** [comment]
Changing the `locale` attribute to `de` seems to work correctly. You can check our HTML code at https://www.openalt.cz/2023/program/.

**Comment by rixx** [comment]
Closed in 2b579d5
