### ISSUE TITLE
Make date-headings larger and more noticeable

### ISSUE THREAD

**Issue by Findus23** [pretalx/schedule#5]
At the moment one can easily miss where one day starts and another days starts in both the grid and the list view. Especially as (I think) a lot of people don't expect days to be shown below each other, it seems quite important to me to make this a lot more noticeable.

For the list view this could be done rather easily by adding something like `font-size: 2rem;text-align: center;` to `.bucket-label . day`. For the grid view it is a bit harder as I don't know css grids well, but it would still be great if the `Fri 05. Nov` was quite a bit larger and centered. My ugly workaround would be to edit `.timeslice.datebreak` to remove `white-space: pre;` and add `font-size: 2rem;`.

![grafik](https://user-images.githubusercontent.com/6266037/134330473-3e89152a-3602-42b2-ac7c-5e8015a3372e.png)
![grafik](https://user-images.githubusercontent.com/6266037/134330521-cc118bbc-23f1-4091-90a0-b445bdc5abf0.png)

Maybe you have a better solution we could implement for our event.

**Comment by rashfael** [comment]
Making the day string more prominent in the list view is a good suggestion, but in the grid view we are constrained by the width of the column, and cannot overlap into the room column to the right, since there might be sessions going from 23:00 PM until 1:00 AM  for example.

**Comment by rixx** [comment]
I thought making it larger would be necessary, but just making it bold made it look much more prominent, so I think this is fine now.
